fix: cbook.Stack() is deprecated at matplotlib >= 3.8.0rc1
Matplotlib made the method """Private""" by modifying Stack() to
_Stack() at commit: ca2c0ff2abf41beb7b69f17bd5caad970812ad85
exactly July 12 of 2023.

If you try running the widget mp-007 at matplotlib version after
July 12 of 2023 it will throw an exception:

AttributeError: module 'matplotlib.cbook' has no attribute 'Stack'. Did you mean: '_Stack'?

So I just modified the lines with cbook.Stack() with cbook._Stack() and
the exception dissapears.

I think it's good to use newer versions because of:
    1. New API
    2. Faster methods
    3. Better Documentation